id: P6FFBA77A
initial_creation_type: ocr
source_metadata:
  volumes:
    18123a09e28b40a89b9d7bd64b6f6bb1:
      base_file: v067.txt
      image_group_id: I1PD95912
      title: འཕགས་པ་སཱ་ལུ་ལྗང་པ་རྒྱ་ཆེར་འགྲེལ་པ།
      total_pages: 1529
      volume_number: 67
