id: D940156F2
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-31T07:01:30+00:00'
last_modified: '2022-05-29T07:49:31.661597+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    8d6d:
      image_group_id: I1PD95912
      title: འཕགས་པ་སཱ་ལུ་ལྗང་པ་རྒྱ་ཆེར་འགྲེལ་པ།
      total_pages: 1529
      order: 67
      base_file: 8d6d.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
